name: Build Bliss

on:
  release:
    types: [ "published" ]
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  # Build Bliss
  build:
    runs-on: ubuntu-latest

    # Run
    steps:
    - uses: actions/checkout@v4

    # Setup .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore

    # Build Bliss
    - name: Build
      run: dotnet build --no-restore

    # Test
    - name: Test
      run: dotnet test --no-build --verbosity normal
